# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Dushyant Kumar
tagline:          'Polymath'
description:      'Polymath, Machine Learning, Deep learning, Data Science, statistics.'
url:
baseurl:          /

author:
  name:           'Dushyant Kumar'
  url:            https://twitter.com/6dushyantmishra20101

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zero1hac/zero1hac.github.io

# Gems
plugins: [jekyll-paginate, jekyll-gist]
